name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image as Default mode 
      run: |
        pwd
        cd ..
        ls -ltr
        export DOCKER_BUILDKIT=1
        docker config ls
        docker build . --file ./polycube/Dockerfile --tag default-github-action-test:$(date +%s)
